create table if not exists public.lead_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  company_name text,
  subject text,
  message text not null,
  source text not null default 'home_contact_form',
  locale text,
  status text not null default 'new' check (status in ('new', 'reviewed', 'contacted', 'converted', 'closed')),
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.workspace_bootstrap_states (
  owner_user_id uuid primary key references auth.users (id) on delete cascade,
  bootstrap_mode text not null default 'demo_seed' check (bootstrap_mode in ('demo_seed')),
  bootstrap_source text not null check (bootstrap_source in ('auto', 'manual', 'existing_data')),
  created_demo_data boolean not null default false,
  bootstrapped_by_email text,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

alter table public.lead_requests enable row level security;
alter table public.workspace_bootstrap_states enable row level security;

revoke all on table public.lead_requests from anon, authenticated;
revoke all on table public.workspace_bootstrap_states from anon, authenticated;
revoke all on sequence public.lead_requests_id_seq from anon, authenticated;

grant all on table public.lead_requests to service_role;
grant all on table public.workspace_bootstrap_states to service_role;
grant usage, select on sequence public.lead_requests_id_seq to service_role;
