-- Migration: 20260910100000_v4_faithful_attendance_tables.sql
-- Purpose: Create isolated Admin V4 attendance tables linked to workspace_employees.

-- 1. Workspace Attendance Configuration (per tenant/warehouse)
create table if not exists public.workspace_attendance_config (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  warehouse_code text not null default 'TH',
  start_shift text not null default '08:30',
  end_shift text not null default '17:30',
  break_start text not null default '12:00',
  break_end text not null default '13:00',
  standard_hours numeric(5,2) not null default 8,
  ot_hourly_fee numeric(12,2) not null default 50,
  overtime_rule_enabled boolean not null default false,
  holiday_dates jsonb not null default '[]'::jsonb,
  currency text not null default 'THB',
  company_address text default '',
  company_lat numeric(10,7) default 0,
  company_lng numeric(10,7) default 0,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  constraint uq_workspace_attendance_config_owner_wh unique (owner_user_id, warehouse_code)
);

-- 2. Workspace Attendance Records (punches & adjustments)
create table if not exists public.workspace_attendance_records (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  employee_id bigint not null references public.workspace_employees (id) on delete cascade,
  warehouse_code text not null default 'TH',
  date date not null,
  in_time text,
  out_time text,
  type text not null default 'normal',
  note text default '',
  in_lat numeric(10,7),
  in_lng numeric(10,7),
  in_distance numeric(10,2),
  in_deviated boolean default false,
  out_lat numeric(10,7),
  out_lng numeric(10,7),
  out_distance numeric(10,2),
  out_deviated boolean default false,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  constraint uq_workspace_attendance_records_emp_date unique (owner_user_id, employee_id, date)
);

create index if not exists idx_workspace_attendance_records_owner_date
  on public.workspace_attendance_records (owner_user_id, warehouse_code, date);

-- 3. Workspace Attendance Calculation Results (authoritative settled metrics)
create table if not exists public.workspace_attendance_calculation_results (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  employee_id bigint not null references public.workspace_employees (id) on delete cascade,
  attendance_record_id bigint references public.workspace_attendance_records (id) on delete set null,
  warehouse_code text not null default 'TH',
  date date not null,
  raw_in_time text,
  raw_out_time text,
  raw_hours numeric(6,2) not null default 0,
  break_deduction_hours numeric(6,2) not null default 0,
  valid_hours numeric(6,2) not null default 0,
  standard_hours numeric(6,2) not null default 8,
  overtime_raw_hours numeric(6,2) not null default 0,
  overtime_pay_hours numeric(6,2) not null default 0,
  work_pay numeric(12,2) not null default 0,
  overtime_pay numeric(12,2) not null default 0,
  meal_allowance_amount numeric(12,2) not null default 0,
  social_security_amount numeric(12,2) not null default 0,
  service_fee_amount numeric(12,2) not null default 0,
  total_pay numeric(12,2) not null default 0,
  status text not null default 'normal',
  calculation_phase text not null default 'settled',
  generated_by text not null default 'calculation',
  settled_at timestamptz default timezone('utc'::text, now()),
  has_exception boolean not null default false,
  exception_reason text,
  note text default '',
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  constraint uq_workspace_att_calc_results_emp_date unique (owner_user_id, employee_id, date)
);

create index if not exists idx_workspace_att_calc_results_owner_date
  on public.workspace_attendance_calculation_results (owner_user_id, warehouse_code, date);

-- Enable RLS and grant service_role permissions
alter table public.workspace_attendance_config enable row level security;
alter table public.workspace_attendance_records enable row level security;
alter table public.workspace_attendance_calculation_results enable row level security;

grant all on public.workspace_attendance_config to service_role, postgres;
grant all on public.workspace_attendance_records to service_role, postgres;
grant all on public.workspace_attendance_calculation_results to service_role, postgres;
