-- Migration: 20260909130000_v4_isolated_employee_tables.sql
-- Purpose: Create isolated Admin V4 employee tables without modifying legacy tables.

-- 1. V4 Dedicated Attendance Rules
create table if not exists public.workspace_attendance_rules (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  warehouse_code text not null default 'TH',
  name text not null default '默认考勤规则',
  is_active boolean not null default true,
  effective_start_date date not null default current_date,
  start_shift text not null default '08:30',
  end_shift text not null default '17:30',
  break_start text not null default '12:00',
  break_end text not null default '13:00',
  standard_hours numeric(5,2) not null default 8,
  overtime_enabled boolean not null default true,
  ot_hourly_fee numeric(12,2) not null default 0,
  overtime_min_unit_hours numeric(5,2) not null default 0.5,
  overtime_rounding text not null default 'floor_to_half_hour',
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists idx_workspace_attendance_rules_owner_wh
  on public.workspace_attendance_rules (owner_user_id, warehouse_code);

-- 2. V4 Dedicated Employees Table (Explicit warehouse binding + decoupled nationality)
create table if not exists public.workspace_employees (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  warehouse_code text not null default 'TH',
  employee_no text not null,
  name text not null,
  nickname text not null default '',
  gender text not null check (gender in ('male', 'female')),
  nationality text not null default 'MM',
  country text not null default 'MM',
  phone text not null default '',
  role text not null default '',
  dept text not null default '',
  join_date date not null,
  status text not null default 'active' check (status in ('active', 'on_leave', 'probation', 'resigned')),
  attendance_rule_id bigint references public.workspace_attendance_rules (id) on delete set null,
  salary_type text not null default 'hourly' check (salary_type in ('fixed', 'hourly')),
  hourly_rate numeric(12,2),
  fixed_salary numeric(12,2),
  overtime_hourly_fee numeric(12,2),
  overtime_rule_enabled boolean default true,
  is_dispatch_personnel boolean not null default false,
  attendance_bonus numeric(12,2) not null default 0 check (attendance_bonus >= 0),
  social_security numeric(12,2) not null default 0 check (social_security >= 0),
  meal_allowance numeric(12,2) not null default 0 check (meal_allowance >= 0),
  service_fee_rate numeric(8,4) not null default 0 check (service_fee_rate >= 0),
  currency text not null default 'THB',
  bank_card_number text,
  bank_name text,
  id_card text,
  photo text,
  is_deleted boolean not null default false,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  constraint workspace_employees_salary_mode_check check (
    (salary_type = 'fixed' and fixed_salary is not null and fixed_salary >= 0)
    or
    (salary_type = 'hourly' and hourly_rate is not null and hourly_rate >= 0)
  ),
  unique (owner_user_id, employee_no)
);

create index if not exists idx_workspace_employees_lookup
  on public.workspace_employees (owner_user_id, warehouse_code)
  where is_deleted = false;

create index if not exists idx_workspace_employees_status
  on public.workspace_employees (owner_user_id, status)
  where is_deleted = false;

-- 3. V4 Dedicated Salary Profiles
create table if not exists public.workspace_salary_profiles (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  employee_id bigint not null references public.workspace_employees (id) on delete cascade,
  effective_start_date date not null,
  effective_end_date date,
  salary_type text not null check (salary_type in ('fixed', 'hourly')),
  hourly_rate numeric(12,2),
  fixed_salary numeric(12,2),
  attendance_bonus numeric(12,2) not null default 0,
  social_security numeric(12,2) not null default 0,
  meal_allowance numeric(12,2) not null default 0,
  service_fee_rate numeric(8,4) not null default 0,
  currency text not null default 'THB',
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists idx_workspace_salary_profiles_emp
  on public.workspace_salary_profiles (owner_user_id, employee_id);

-- 4. Relax foreign key constraint on workspace_accounts so employee_id can link to workspace_employees
alter table public.workspace_accounts
  drop constraint if exists workspace_accounts_employee_id_fkey;

-- 5. Row Level Security & Service Role Grants
alter table public.workspace_attendance_rules enable row level security;
alter table public.workspace_employees enable row level security;
alter table public.workspace_salary_profiles enable row level security;

revoke all on table public.workspace_attendance_rules from anon, authenticated;
revoke all on table public.workspace_employees from anon, authenticated;
revoke all on table public.workspace_salary_profiles from anon, authenticated;

grant select, insert, update, delete on table public.workspace_attendance_rules to service_role;
grant select, insert, update, delete on table public.workspace_employees to service_role;
grant select, insert, update, delete on table public.workspace_salary_profiles to service_role;

grant usage, select on sequence public.workspace_attendance_rules_id_seq to service_role;
grant usage, select on sequence public.workspace_employees_id_seq to service_role;
grant usage, select on sequence public.workspace_salary_profiles_id_seq to service_role;
