-- Migration: 20260919120000_create_workspace_invoices.sql
-- Purpose: Dedicated Admin V4 isolated invoice persistence table.

CREATE TABLE IF NOT EXISTS public.workspace_invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  warehouse_code TEXT NOT NULL DEFAULT 'TH',
  invoice_no TEXT NOT NULL,
  customer_id TEXT NOT NULL DEFAULT '',
  customer_name TEXT NOT NULL DEFAULT '',
  invoice_type TEXT NOT NULL DEFAULT '增值税专用发票',
  copy_text TEXT NOT NULL DEFAULT '第一联 记账联',
  currency TEXT NOT NULL DEFAULT 'CNY',
  
  -- Financial Amount Fields
  subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  tax_rate NUMERIC(5, 2) NOT NULL DEFAULT 0.00,
  tax_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  
  -- Dates and Status
  issue_date DATE NOT NULL DEFAULT CURRENT_DATE,
  due_date DATE,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'pending', 'paid', 'overdue', 'canceled')),
  
  -- Seller Details Snapshot
  seller_name TEXT NOT NULL DEFAULT '',
  seller_tax_no TEXT NOT NULL DEFAULT '',
  seller_bank_name TEXT NOT NULL DEFAULT '',
  seller_bank_account TEXT NOT NULL DEFAULT '',
  seller_address TEXT NOT NULL DEFAULT '',
  seller_phone TEXT NOT NULL DEFAULT '',
  seller_contact TEXT NOT NULL DEFAULT '',
  seller_logo TEXT,
  seller_signature TEXT,
  seller_stamp TEXT,
  sig_x INT NOT NULL DEFAULT 0,
  sig_y INT NOT NULL DEFAULT 0,
  stamp_x INT NOT NULL DEFAULT 0,
  stamp_y INT NOT NULL DEFAULT 0,

  -- Buyer Details Snapshot
  buyer_tax_no TEXT NOT NULL DEFAULT '',
  buyer_bank_name TEXT NOT NULL DEFAULT '',
  buyer_bank_account TEXT NOT NULL DEFAULT '',
  buyer_address TEXT NOT NULL DEFAULT '',
  buyer_phone TEXT NOT NULL DEFAULT '',
  buyer_contact TEXT NOT NULL DEFAULT '',
  buyer_logo TEXT,

  -- Line items (JSONB)
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  note TEXT NOT NULL DEFAULT '',
  pdf_url TEXT,

  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),

  CONSTRAINT uk_workspace_invoices_owner_wh_no UNIQUE (owner_user_id, warehouse_code, invoice_no)
);

CREATE INDEX IF NOT EXISTS idx_workspace_invoices_query
  ON public.workspace_invoices (owner_user_id, warehouse_code, status, issue_date DESC)
  WHERE is_deleted = FALSE;

CREATE INDEX IF NOT EXISTS idx_workspace_invoices_customer
  ON public.workspace_invoices (owner_user_id, customer_id)
  WHERE is_deleted = FALSE;

ALTER TABLE public.workspace_invoices ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.workspace_invoices FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.workspace_invoices TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.workspace_invoices_id_seq TO service_role;
