-- Current-state baseline for the rebuilt wmshr Supabase project.
-- Legacy migrations before 2026-07-15 were incremental patches against the deleted project and
-- did not include the original core tables. Keep this file self-contained so a fresh empty
-- Supabase project can be restored with one `supabase db push`.

alter default privileges for role postgres in schema public
  revoke select, insert, update, delete on tables from anon, authenticated, service_role;

alter default privileges for role postgres in schema public
  revoke usage, select on sequences from anon, authenticated, service_role;

create table if not exists public.admin_owner_email_links (
  email text primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  created_by_auth_user_id uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  constraint admin_owner_email_links_email_normalized
    check (email = lower(btrim(email)) and position('@' in email) > 1)
);

create table if not exists public.admin_owner_identity_links (
  auth_user_id uuid primary key references auth.users (id) on delete cascade,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  email text not null references public.admin_owner_email_links (email) on update cascade on delete cascade,
  provider text,
  providers text[] not null default '{}',
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  last_seen_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.lead_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  company_name text,
  subject text,
  message text not null,
  source text not null default 'home_contact_form',
  locale text,
  status text not null default 'new' check (status in ('new', 'reviewed', 'contacted', 'converted', 'closed')),
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.workspace_bootstrap_states (
  owner_user_id uuid primary key references auth.users (id) on delete cascade,
  bootstrap_mode text not null default 'demo_seed' check (bootstrap_mode in ('demo_seed')),
  bootstrap_source text not null check (bootstrap_source in ('auto', 'manual', 'existing_data')),
  created_demo_data boolean not null default false,
  bootstrapped_by_email text,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.attendance_rules (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  name text not null,
  is_active boolean not null default true,
  effective_start_date date,
  effective_end_date date,
  start_shift time not null default '08:30',
  end_shift time not null default '17:30',
  break_start time not null default '12:00',
  break_end time not null default '13:00',
  standard_hours numeric(6,2) not null default 8 check (standard_hours >= 0),
  overtime_enabled boolean not null default true,
  ot_hourly_fee numeric(12,2) not null default 50 check (ot_hourly_fee >= 0),
  overtime_min_unit_hours numeric(6,2) not null default 0.5 check (overtime_min_unit_hours > 0),
  overtime_rounding text not null default 'floor_to_half_hour'
    check (overtime_rounding in ('none', 'floor_to_half_hour', 'ceil_to_half_hour', 'round_to_half_hour')),
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  check (effective_end_date is null or effective_start_date is null or effective_end_date >= effective_start_date)
);

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  employee_no text not null,
  name text not null,
  nickname text not null default '',
  gender text not null check (gender in ('male', 'female')),
  country text not null check (country in ('MM', 'TH', 'CN', 'VN', 'KH')),
  phone text not null default '',
  role text not null default '',
  dept text not null default '',
  join_date date not null,
  status text not null default 'active' check (status in ('active', 'on_leave', 'probation', 'resigned')),
  attendance_rule_id bigint references public.attendance_rules (id) on delete set null,
  salary_type text not null check (salary_type in ('fixed', 'hourly')),
  hourly_rate numeric(12,2),
  fixed_salary numeric(12,2),
  overtime_hourly_fee numeric(12,2),
  overtime_rule_enabled boolean,
  is_dispatch_personnel boolean not null default false,
  attendance_bonus numeric(12,2) not null default 0 check (attendance_bonus >= 0),
  social_security numeric(12,2) not null default 0 check (social_security >= 0),
  meal_allowance numeric(12,2) not null default 0 check (meal_allowance >= 0),
  service_fee_rate numeric(8,4) not null default 0 check (service_fee_rate >= 0),
  currency text not null default 'THB' check (currency in ('THB', 'USD', 'MYR', 'IDR')),
  photo text,
  is_deleted boolean not null default false,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  constraint employees_salary_mode_check check (
    (salary_type = 'fixed' and fixed_salary is not null and fixed_salary >= 0 and hourly_rate is null)
    or
    (salary_type = 'hourly' and hourly_rate is not null and hourly_rate >= 0 and fixed_salary is null)
  ),
  unique (owner_user_id, employee_no)
);

create table if not exists public.employee_attendance_rule_history (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  employee_id bigint not null references public.employees (id) on delete cascade,
  attendance_rule_id bigint references public.attendance_rules (id) on delete set null,
  attendance_rule_name text,
  effective_start_date date not null,
  effective_end_date date,
  created_at timestamptz not null default timezone('utc'::text, now()),
  created_by text,
  check (effective_end_date is null or effective_end_date >= effective_start_date)
);

create table if not exists public.attendance_config (
  owner_user_id uuid primary key references auth.users (id) on delete cascade,
  start_shift time not null default '08:30',
  end_shift time not null default '17:30',
  break_start time not null default '12:00',
  break_end time not null default '13:00',
  standard_hours numeric(6,2) not null default 8 check (standard_hours >= 0),
  ot_hourly_fee numeric(12,2) not null default 50 check (ot_hourly_fee >= 0),
  currency text not null default 'THB' check (currency in ('THB', 'USD', 'MYR', 'IDR')),
  overtime_rule_enabled boolean not null default false,
  holiday_dates date[] not null default '{}',
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.leave_requests (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  employee_id bigint not null references public.employees(id) on delete cascade,
  type text not null check (type in ('personal', 'sick', 'annual', 'special')),
  start_date date not null,
  end_date date not null,
  duration_days integer not null check (duration_days > 0),
  reason text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  submitted_at timestamptz not null default now(),
  approved_at timestamptz,
  rejected_at timestamptz,
  approver_user_id uuid references auth.users (id) on delete set null,
  approval_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_date >= start_date)
);

create table if not exists public.attendance_records (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  employee_id bigint not null references public.employees(id) on delete cascade,
  date date not null,
  in_time time,
  out_time time,
  type text not null check (type in ('normal', 'late', 'early', 'absent', 'leave', 'sick_leave', 'overtime')),
  source text not null default 'manual' check (source in ('manual', 'import', 'system', 'device', 'mobile')),
  note text not null default '',
  manual_overtime_hourly_fee numeric(12,2),
  manual_overtime_use_rule boolean,
  leave_request_id bigint references public.leave_requests(id) on delete set null,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  unique (owner_user_id, employee_id, date)
);

create table if not exists public.attendance_calculation_results (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  employee_id bigint not null references public.employees(id) on delete cascade,
  attendance_record_id bigint references public.attendance_records(id) on delete set null,
  date date not null,
  attendance_rule_id bigint references public.attendance_rules(id) on delete set null,
  attendance_rule_name text,
  raw_in_time time,
  raw_out_time time,
  raw_hours numeric(10,2) not null default 0,
  break_deduction_hours numeric(10,2) not null default 0,
  valid_hours numeric(10,2) not null default 0,
  standard_hours numeric(10,2) not null default 0,
  overtime_raw_hours numeric(10,2) not null default 0,
  overtime_pay_hours numeric(10,2) not null default 0,
  work_pay numeric(12,2) not null default 0,
  meal_allowance_amount numeric(12,2) not null default 0 check (meal_allowance_amount >= 0),
  overtime_pay numeric(12,2) not null default 0,
  total_pay numeric(12,2) not null default 0,
  status text not null check (status in ('pending', 'checked_in', 'normal', 'late', 'early', 'leave', 'sick_leave', 'absent', 'overtime', 'manual_adjusted', 'exception')),
  source text not null default 'system' check (source in ('manual', 'import', 'system', 'device', 'mobile')),
  calculation_phase text not null default 'settled' check (calculation_phase in ('draft', 'settled')),
  generated_by text not null default 'calculation' check (generated_by in ('calculation', 'draft_job', 'settlement_job', 'manual_recalculate')),
  settled_at timestamptz,
  has_exception boolean not null default false,
  exception_reason text,
  note text not null default '',
  calculated_at timestamptz not null default timezone('utc'::text, now()),
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  unique (owner_user_id, employee_id, date)
);

create table if not exists public.monthly_attendance_summaries (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  employee_id bigint not null references public.employees(id) on delete cascade,
  year_month text not null check (year_month ~ '^\d{4}-\d{2}$'),
  period_start_date date not null,
  period_end_date date not null,
  total_raw_hours numeric(10,2) not null default 0,
  total_break_deduction_hours numeric(10,2) not null default 0,
  total_valid_hours numeric(10,2) not null default 0,
  total_standard_hours numeric(10,2) not null default 0,
  total_overtime_raw_hours numeric(10,2) not null default 0,
  total_overtime_pay_hours numeric(10,2) not null default 0,
  record_count integer not null default 0,
  exception_count integer not null default 0,
  absent_count integer not null default 0,
  leave_count integer not null default 0,
  manual_adjusted_count integer not null default 0,
  can_generate_payroll boolean not null default false,
  blocked_reason text,
  calculated_at timestamptz not null default timezone('utc'::text, now()),
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  unique (owner_user_id, employee_id, year_month)
);

create table if not exists public.salary_profiles (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  employee_id bigint not null references public.employees(id) on delete cascade,
  salary_type text not null check (salary_type in ('fixed', 'hourly')),
  fixed_salary numeric(12,2),
  hourly_rate numeric(12,2),
  service_fee_rate numeric(8,4) not null default 0 check (service_fee_rate >= 0),
  currency text not null check (currency in ('THB', 'USD', 'MYR', 'IDR')),
  is_active boolean not null default true,
  effective_start_date date,
  effective_end_date date,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  constraint salary_profiles_salary_mode_check check (
    (salary_type = 'fixed' and fixed_salary is not null and fixed_salary >= 0 and hourly_rate is null)
    or
    (salary_type = 'hourly' and hourly_rate is not null and hourly_rate >= 0 and fixed_salary is null)
  )
);

create table if not exists public.salary_adjustment_items (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  employee_id bigint not null references public.employees(id) on delete cascade,
  year_month text not null check (year_month ~ '^\d{4}-\d{2}$'),
  type text not null check (type in ('allowance', 'deduction', 'other')),
  name text not null check (btrim(name) <> ''),
  amount numeric(12,2) not null check (amount >= 0),
  note text not null default '',
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.monthly_payroll_results (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  employee_id bigint not null references public.employees(id) on delete cascade,
  year_month text not null check (year_month ~ '^\d{4}-\d{2}$'),
  salary_type text not null check (salary_type in ('fixed', 'hourly')),
  fixed_salary numeric(12,2),
  hourly_rate numeric(12,2),
  currency text not null check (currency in ('THB', 'USD', 'MYR', 'IDR')),
  valid_hours numeric(10,2) not null default 0,
  standard_hours numeric(10,2) not null default 0,
  hourly_pay numeric(12,2) not null default 0,
  overtime_pay_hours numeric(10,2) not null default 0,
  overtime_pay numeric(12,2) not null default 0,
  allowance_total numeric(12,2) not null default 0,
  deduction_total numeric(12,2) not null default 0,
  other_total numeric(12,2) not null default 0,
  social_security_amount numeric(12,2) not null default 0 check (social_security_amount >= 0),
  service_fee_amount numeric(12,2) not null default 0 check (service_fee_amount >= 0),
  gross_pay numeric(12,2) not null default 0,
  total_deduction numeric(12,2) not null default 0,
  net_pay numeric(12,2) not null default 0,
  calculation_status text not null default 'draft' check (calculation_status in ('draft', 'calculated', 'blocked', 'confirmed')),
  review_status text not null default 'pending' check (review_status in ('pending', 'approved', 'rejected')),
  blocked_reason text,
  calculated_at timestamptz,
  confirmed_at timestamptz,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  constraint monthly_payroll_results_salary_mode_check check (
    (salary_type = 'fixed' and fixed_salary is not null and fixed_salary >= 0 and hourly_rate is null)
    or
    (salary_type = 'hourly' and hourly_rate is not null and hourly_rate >= 0 and fixed_salary is null)
  ),
  unique (owner_user_id, employee_id, year_month)
);

create table if not exists public.employee_app_accounts (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  employee_id bigint not null references public.employees(id) on delete cascade,
  account text not null,
  password_hash text not null,
  status text not null default 'active' check (status in ('active', 'disabled')),
  password_updated_at timestamptz not null default timezone('utc'::text, now()),
  last_login_at timestamptz,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  unique (owner_user_id, employee_id),
  unique (owner_user_id, account)
);

create table if not exists public.employee_notifications (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  employee_id bigint not null references public.employees(id) on delete cascade,
  type text not null check (type in ('payroll_confirmed')),
  title text not null,
  content text not null default '',
  biz_id bigint,
  biz_month text,
  read_at timestamptz,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  unique (owner_user_id, employee_id, type, biz_id)
);

create table if not exists public.sop_documents (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  title text not null,
  content_html text not null,
  target_type text not null default 'all' check (target_type in ('all', 'specific')),
  creator text not null,
  status text not null default 'published' check (status in ('draft', 'published')),
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.sop_document_targets (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  sop_id bigint not null references public.sop_documents(id) on delete cascade,
  employee_id bigint not null references public.employees(id) on delete cascade,
  created_at timestamptz not null default timezone('utc'::text, now()),
  unique (owner_user_id, sop_id, employee_id)
);

create table if not exists public.sop_assets (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  sop_id bigint not null references public.sop_documents(id) on delete cascade,
  kind text not null check (kind in ('image', 'attachment')),
  name text not null,
  url text not null,
  size_label text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.sop_reads (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  sop_id bigint not null references public.sop_documents(id) on delete cascade,
  employee_id bigint not null references public.employees(id) on delete cascade,
  read_at timestamptz not null default timezone('utc'::text, now()),
  unique (owner_user_id, sop_id, employee_id)
);

create table if not exists public.customer_accounts (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  customer_code text not null,
  name text not null,
  contact text not null default '',
  currency text not null default 'CNY',
  available_limit numeric(14,2) not null default 0,
  credit_limit numeric(14,2) not null default 0,
  billing_template text not null default '',
  status text not null default 'enabled' check (status in ('enabled', 'disabled')),
  shops jsonb not null default '[]'::jsonb,
  credit_logs jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  unique (owner_user_id, customer_code)
);

create table if not exists public.admin_goods_snapshots (
  owner_user_id uuid primary key references auth.users(id) on delete cascade,
  snapshot jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.admin_expense_snapshots (
  owner_user_id uuid primary key references auth.users(id) on delete cascade,
  expenses jsonb not null default '[]'::jsonb,
  categories jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.mobile_app_releases (
  platform text primary key check (platform in ('android')),
  version text not null,
  content text not null,
  url text not null,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create unique index if not exists attendance_rules_owner_name_unique
  on public.attendance_rules (owner_user_id, name);
create index if not exists idx_admin_owner_identity_links_owner
  on public.admin_owner_identity_links (owner_user_id);
create index if not exists idx_admin_owner_identity_links_email
  on public.admin_owner_identity_links (email);
create index if not exists idx_employee_rule_history_owner_employee
  on public.employee_attendance_rule_history(owner_user_id, employee_id, effective_start_date desc);
create index if not exists idx_employee_rule_history_owner_rule
  on public.employee_attendance_rule_history(owner_user_id, attendance_rule_id);
create index if not exists idx_employees_owner_id
  on public.employees(owner_user_id, id);
create index if not exists idx_employees_owner_status_id
  on public.employees(owner_user_id, status, id);
create index if not exists idx_employees_owner_role
  on public.employees(owner_user_id, role);
create index if not exists idx_employees_owner_active_list
  on public.employees(owner_user_id, id)
  where status <> 'resigned';
create index if not exists idx_attendance_records_owner_employee_date
  on public.attendance_records(owner_user_id, employee_id, date desc);
create index if not exists idx_attendance_records_leave_request_id
  on public.attendance_records(leave_request_id);
create index if not exists idx_attendance_calc_results_owner_date_desc
  on public.attendance_calculation_results (owner_user_id, date desc);
create index if not exists idx_attendance_calc_results_owner_employee_date
  on public.attendance_calculation_results (owner_user_id, employee_id, date desc);
create index if not exists idx_monthly_summaries_owner_month
  on public.monthly_attendance_summaries(owner_user_id, year_month, employee_id);
create index if not exists idx_salary_profiles_owner_employee_effective
  on public.salary_profiles(owner_user_id, employee_id, effective_start_date desc, id desc);
create index if not exists idx_salary_adjustment_items_owner_employee_month
  on public.salary_adjustment_items(owner_user_id, employee_id, year_month, created_at desc);
create index if not exists idx_monthly_payroll_results_owner_month
  on public.monthly_payroll_results(owner_user_id, year_month, employee_id);
create index if not exists idx_employee_app_accounts_owner_account
  on public.employee_app_accounts(owner_user_id, account);
create index if not exists idx_employee_app_accounts_employee
  on public.employee_app_accounts(owner_user_id, employee_id);
create unique index if not exists employee_app_accounts_account_global_unique
  on public.employee_app_accounts(account);
create index if not exists idx_employee_notifications_owner_employee_created
  on public.employee_notifications(owner_user_id, employee_id, created_at desc);
create index if not exists idx_employee_notifications_owner_employee_unread
  on public.employee_notifications(owner_user_id, employee_id, read_at, created_at desc);
create index if not exists idx_employee_notifications_owner_biz
  on public.employee_notifications(owner_user_id, type, biz_id);
create index if not exists idx_leave_requests_owner_employee_created
  on public.leave_requests(owner_user_id, employee_id, created_at desc);
create index if not exists idx_leave_requests_owner_status_created
  on public.leave_requests(owner_user_id, status, created_at desc);
create index if not exists idx_leave_requests_owner_employee_start_end
  on public.leave_requests(owner_user_id, employee_id, start_date, end_date);
create index if not exists idx_sop_documents_owner_status_created
  on public.sop_documents(owner_user_id, status, created_at desc);
create index if not exists idx_sop_documents_owner_title
  on public.sop_documents(owner_user_id, title);
create index if not exists idx_sop_targets_owner_employee
  on public.sop_document_targets(owner_user_id, employee_id, sop_id);
create index if not exists idx_sop_assets_owner_sop_order
  on public.sop_assets(owner_user_id, sop_id, kind, sort_order);
create index if not exists idx_sop_reads_owner_sop
  on public.sop_reads(owner_user_id, sop_id, employee_id);
create index if not exists idx_sop_reads_owner_employee
  on public.sop_reads(owner_user_id, employee_id, sop_id);
create index if not exists idx_customer_accounts_owner_status_updated
  on public.customer_accounts(owner_user_id, status, updated_at desc);
create index if not exists idx_customer_accounts_owner_name
  on public.customer_accounts(owner_user_id, name);
create index if not exists admin_goods_snapshots_updated_at_idx
  on public.admin_goods_snapshots (updated_at desc);
create index if not exists admin_expense_snapshots_updated_at_idx
  on public.admin_expense_snapshots (updated_at desc);

alter table public.admin_owner_email_links enable row level security;
alter table public.admin_owner_identity_links enable row level security;
alter table public.lead_requests enable row level security;
alter table public.workspace_bootstrap_states enable row level security;
alter table public.attendance_rules enable row level security;
alter table public.employees enable row level security;
alter table public.employee_attendance_rule_history enable row level security;
alter table public.attendance_config enable row level security;
alter table public.leave_requests enable row level security;
alter table public.attendance_records enable row level security;
alter table public.attendance_calculation_results enable row level security;
alter table public.monthly_attendance_summaries enable row level security;
alter table public.salary_profiles enable row level security;
alter table public.salary_adjustment_items enable row level security;
alter table public.monthly_payroll_results enable row level security;
alter table public.employee_app_accounts enable row level security;
alter table public.employee_notifications enable row level security;
alter table public.sop_documents enable row level security;
alter table public.sop_document_targets enable row level security;
alter table public.sop_assets enable row level security;
alter table public.sop_reads enable row level security;
alter table public.customer_accounts enable row level security;
alter table public.admin_goods_snapshots enable row level security;
alter table public.admin_expense_snapshots enable row level security;
alter table public.mobile_app_releases enable row level security;

comment on table public.employees is
  'Admin service-role owned employee master data. Client roles stay revoked; owner_user_id filtering is enforced in apps/admin/server/index.js.';
comment on table public.attendance_calculation_results is
  'Current v2 attendance result table, including draft/settled metadata used by daily maintenance jobs.';
comment on table public.monthly_payroll_results is
  'Monthly payroll snapshots. Amount fields are persisted so historical payroll does not drift when employee settings change.';
comment on table public.admin_goods_snapshots is
  'Admin v3 goods module account-level snapshot storage; keeps prototype whole-table write UX but persists through service role.';
comment on table public.admin_expense_snapshots is
  'Admin v3 expenses module account-level snapshot storage; stores records and category config together to avoid skew.';
comment on table public.leave_requests is
  'Employee mobile leave request workflow. Approved rows are later reflected into attendance_records.';
comment on column public.attendance_config.overtime_rule_enabled is
  'Whether overtime multiplier rules are enabled. When disabled, overtime uses ot_hourly_fee directly.';
comment on column public.attendance_config.holiday_dates is
  'Owner-maintained holiday dates used for 3x overtime decisions.';
comment on column public.attendance_records.manual_overtime_hourly_fee is
  'Manual override overtime hourly fee for this attendance row; null falls back to employee/account defaults.';
comment on column public.attendance_records.manual_overtime_use_rule is
  'Manual override for multiplier-rule usage; null falls back to employee/account defaults.';
comment on column public.employees.overtime_hourly_fee is
  'Employee-level overtime fee base; null falls back to attendance_config.ot_hourly_fee.';
comment on column public.employees.overtime_rule_enabled is
  'Employee-level multiplier-rule override; null falls back to attendance_config.overtime_rule_enabled.';
comment on column public.employees.is_dispatch_personnel is
  'Dispatch personnel social security is calculated per attendance day; non-dispatch uses monthly fixed deduction.';

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'admin_owner_email_links',
    'admin_owner_identity_links',
    'lead_requests',
    'workspace_bootstrap_states',
    'attendance_rules',
    'employees',
    'employee_attendance_rule_history',
    'attendance_config',
    'leave_requests',
    'attendance_records',
    'attendance_calculation_results',
    'monthly_attendance_summaries',
    'salary_profiles',
    'salary_adjustment_items',
    'monthly_payroll_results',
    'employee_app_accounts',
    'employee_notifications',
    'sop_documents',
    'sop_document_targets',
    'sop_assets',
    'sop_reads',
    'customer_accounts',
    'admin_goods_snapshots',
    'admin_expense_snapshots',
    'mobile_app_releases'
  ] loop
    execute format('revoke all on table public.%I from anon, authenticated', table_name);
    execute format('grant all on table public.%I to service_role', table_name);
  end loop;
end $$;

revoke all on all sequences in schema public from anon, authenticated;
grant usage, select on all sequences in schema public to service_role;
