create table if not exists public.employee_permission_audits (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  actor_id text not null,
  target_employee_id bigint not null references public.employees(id) on delete cascade,
  previous_permissions jsonb not null default '[]'::jsonb,
  next_permissions jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists idx_employee_permission_audits_target
  on public.employee_permission_audits (owner_user_id, target_employee_id, created_at desc);

alter table public.employee_permission_audits enable row level security;
